### ISSUE TITLE
Inconsistencies between WFS capabilities and associated CSW metadata

### ISSUE THREAD

**Issue by cportele** [geo4web-testbed/ldproxy-design#3]
Several differences exist for the BAG WFS and the referenced metadata in the CSW. For example, the bounding boxes differ significantly. The current idea is to use the capabilities as the default/main source.

**Comment by pvgenuchten** [comment]
I'd suggest to give the wfs-metadata preference, since it provides the latest information on updated bounds/dates

**Comment by cportele** [comment]
The issue has been documented in the report.
