### ISSUE TITLE
How to provide processable API documentation

### ISSUE THREAD

**Issue by cportele** [geo4web-testbed/ldproxy-design#5]
Swagger? Hydra? ...?

After discussion at 1st open day: Probably at least swagger.

**Comment by joostfarla** [comment]
Swaggerhub is easy to start with, without having to install all tooling yourself:

https://swaggerhub.com/

Some alternatives are RAML and API Blueprint.

**Comment by cportele** [comment]
Added as an issue in the ldproxy repo.

https://github.com/interactive-instruments/ldproxy/issues/9
