### ISSUE TITLE
BAG test service

### ISSUE THREAD

**Issue by cportele** [geo4web-testbed/ldproxy-design#6]
http://services.interactive-instruments.de/ldproxy/rest/services/bag/

Protected by basic auth until it is ready to be crawled.

**Comment by pvgenuchten** [comment]
- On the detail page Is it useful to have a link back to a getfeatutebyid response as 'point-of-truth'
- No pagination yet?
- On detail page provide links back to list page
- Is it possible to use thing.name as html/head/title (which will be displayed in google search result)

**Comment by azahnen** [comment]
Thanks for the input!
- Points 2 + 3 should be included in the recent update.
- As for 1, you can open the GML using the "View as" options, but there is no WFS request URL included. I think it might be a good idea to include such a link, visible or not, with a "sameAs" mapping, like we do on the dataset page.
- Yes, we should use context sensitive titles.

**Comment by cportele** [comment]
What I noticed:
- Currently there are multiple streetAddress properties (e.g. "Mello Coendersbuurt", "21" and "A"), but there should be only one "Mello Coendersbuurt 21A".
- I think we should add the postalCode also on the collection level.
- Should we add a hasMap property?
- I agree that we should add the WFS request to the Place resource. I am not so sure about using sameAs as this should link to a webpage according to the schema.org definition. But there is also no other property of Place that we could use.
- We need to replace example.com with the URL of the proxy service.

The BAG WFS is slow and so is the proxy. Fortunately the Farmland WFS is much better.

**Comment by cportele** [comment]
The testbed work on the BAG proxy is now complete
