### ISSUE TITLE
Backlink from WFS to CSW

### ISSUE THREAD

**Issue by pvgenuchten** [geo4web-testbed/ldproxy-design#8]
On the proxied wfs-capabilities page and the feature-type page and it's relevant json-ld representations  there should be links back to the service metadata (if capabilities has that link; inspire extension) and the dataset/featuretype metadata. Consider that  there may be 0, 1 or many links in capabilitities

Rules:
- Standard call to the cswproxy will be http://{server}/cswproxy?url=http://{server}/geoportal/csw?REQUEST=GetRecordById&service=CSW&version=2.0.2&Id=FDD685A1-04B9-4CA4-AA2E-8B20E14CF464
- If you detect the csw-server is nationaalgeoregister.nl, you can also use http://{server}/id/dataset/FDD685A1-04B9-4CA4-AA2E-8B20E14CF464

Content negotiation (via the accept header) should return the proper format (html/json-ld/xml) on both endpoints

**Comment by ghost** [comment]
In schema.org we have this sequence:

```
schema:DataCatalog schema:dataset schema:Dataset
```

The backlink (inverse property) does not exist, so I propose to use

```
schema:DataCatalog schema:hasPart schema:Dataset
```

and its inverse:

```
schema:Dataset schema:isPartOf schema:DataCatalog
```

**Comment by cportele** [comment]
@liekeverhelst This looks reasonable to me! Thanks.

**Comment by azahnen** [comment]
@pvgenuchten When trying to use on of these urls I am redirected to the login. Am I doing it wrong?
- http://opendatacat.net/geonetwork-geo4web/id/dataset/76091be7-358a-4a44-8182-b4139c96c6a4
- http://opendatacat.net/geonetwork-geo4web/srv/id/dataset/76091be7-358a-4a44-8182-b4139c96c6a4
- http://opendatacat.net/geonetwork-geo4web/cswproxy?url=...
- http://opendatacat.net/geonetwork-geo4web/srv/cswproxy?url=...

In the meantime I am linking to: http://opendatacat.net/geonetwork-geo4web/doc/dataset/76091be7-358a-4a44-8182-b4139c96c6a4

**Comment by pvgenuchten** [comment]
The csw proxy is not yet available, so those urls will forward to login page

Groet Paul van Genuchten
