### ISSUE TITLE
if a property in the wfs contains a url display as link or image

### ISSUE THREAD

**Issue by pvgenuchten** [geo4web-testbed/ldproxy-design#9]
Nice to have: If a property is modeled as url, or starts with 'http' then display the link in html view as a link <a href={ val }> if a property is modeled as image url or starts with http and ends width gif/jpg/png then display the image in html view <img src={ val }>

**Comment by cportele** [comment]
Moved to https://github.com/interactive-instruments/ldproxy/issues/34 and closed here.
